services:
  fastapi-backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    extra_hosts: # for linux hosts since version 20.10
      - host.docker.internal:host-gateway
    # env_file:
    #   - ./backend/.env
    container_name: fastapi-backend

  chat-react-frontend:
    build:
      context: ./chat-react
    ports:
      - "5173:5173"
    container_name: chat-react-frontend


  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    container_name: qdrant

